### ISSUE TITLE
Frame of the published image 

### ISSUE THREAD

**Issue by sayali-purdue** [Enri2077/rockin_logger#1]
The image published at line 192 in [rockin_logger.cpp](https://github.com/Enri2077/rockin_logger/blob/master/src/rockin_logger.cpp#L192) does not specify its frame information (i.e., frame_id field). I would like to know few details about this frame:
1. why is there no need for the frame info in your application? 
2. as per the [sensor_msgs::Image](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/Image.html) definition, the image frame is usually an optical frame of camera. Does this apply to the published image here? 
3. I think, the frame info is useful for the users of the published data (e.g. proper display of image in RViz). As a developer of this code, do you believe that image's frame info can be required by others who use this application node?

Thank you.

**Comment by Enri2077** [comment]
Hi Sayali, this code is no longer maintained.

**Comment by sayali-purdue** [comment]
Hello Enri, thanks for your reply. I understand that this code is not maintained anymore. However, I would really appreciate if you could provide your perspective on the usefulness of frame info of the published image data. As part of my project, I am collecting developer response and your input would be a valuable addition to it.

**Comment by Enri2077** [comment]
What kind of project?

**Comment by sayali-purdue** [comment]
We are studying about static detection of common errors in ros-based programs.
